global:
  images:
    tags:
      # You can override containers here:
      # nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:master-latest"
      contrail_status: "docker.io/opencontrailnightly/contrail-status:master-latest"
      node_init: "docker.io/opencontrailnightly/contrail-node-init:master-latest"
      analytics_api: "docker.io/opencontrailnightly/contrail-analytics-api:master-latest"
      contrail_collector: "docker.io/opencontrailnightly/contrail-analytics-collector:master-latest"
      analytics_alarm_gen: "docker.io/opencontrailnightly/contrail-analytics-alarm-gen:master-latest"
      analytics_snmp_collector: "docker.io/opencontrailnightly/contrail-analytics-snmp-collector:master-latest"
      contrail_topology: "docker.io/opencontrailnightly/contrail-analytics-snmp-topology:master-latest"
      dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password

  contrail_env:
    CONTROLLER_NODES: 10.87.65.248
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    ANALYTICSDB_ENABLE: "true"
    ANALYTICS_ALARM_ENABLE: "true"
    ANALYTICS_SNMP_ENABLE: "true"

labels:
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_snmp:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_alarm:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"


dependencies:
  analytics:
    daemonset:
    - contrail-config
  analytics_snmp:
    daemonset:
    - contrail-config
  analytics_alarm:
    daemonset:
    - contrail-config

# Names of secrets used by bootstrap and environmental checks
secrets:
  keystone:
    admin: contrail-analytics-keystone-admin

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  rabbitmq:
    auth:
      username: guest
      password: guest
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5673
    hosts:
      default: rabbitmq
    host_fqdn_override:
       default: null
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone
    path:
      default: /v3
    port:
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null
    namespace: openstack

pod:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        analytics:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1

# Service related inputs are defined here
service:
  analytics_api_public_port: ""

# Ingress related inputs are defined here
ingress:
  analytics_api_host: "contrail-analytics-api"

# VolumeMounts related inputs are defined here
volumeMounts:
  host_usr_bin:
    hostPath: '/usr/bin'

manifests:
  configmap_analytics_env: true
  configmap_analytics_keystone: true
  configmap_analytics_rabbitmq: true
  daemonset_analytics: true
  daemonset_analytics_snmp: true
  daemonset_analytics_alarm: true
  service_analytics_api_server: true
  service_analytics_api_ingress: true
  ingress_analytics_api: true
  secret_analytics_keystone_admin: true
