# GLOBAL variables: which can be consumed by all charts
# images, contrail_env, contrail_env_vrouter_dpdk, contrail_env_vrouter_kernel
global:
  # section to configure images for all containers
  images:
    tags:
      kafka: "docker.io/opencontrailnightly/contrail-external-kafka:master-latest"
      cassandra: "docker.io/opencontrailnightly/contrail-external-cassandra:master-latest"
      redis: "docker.io/opencontrailnightly/contrail-external-redis:master-latest"
      zookeeper: "docker.io/opencontrailnightly/contrail-external-zookeeper:master-latest"
      contrail_control: "docker.io/opencontrailnightly/contrail-controller-control-control:master-latest"
      control_dns: "docker.io/opencontrailnightly/contrail-controller-control-dns:master-latest"
      control_named: "docker.io/opencontrailnightly/contrail-controller-control-named:master-latest"
      config_api: "docker.io/opencontrailnightly/contrail-controller-config-api:master-latest"
      config_devicemgr: "docker.io/opencontrailnightly/contrail-controller-config-devicemgr:master-latest"
      config_schema_transformer: "docker.io/opencontrailnightly/contrail-controller-config-schema:master-latest"
      config_svcmonitor: "docker.io/opencontrailnightly/contrail-controller-config-svcmonitor:master-latest"
      webui_middleware: "docker.io/opencontrailnightly/contrail-controller-webui-job:master-latest"
      webui: "docker.io/opencontrailnightly/contrail-controller-webui-web:master-latest"
      analytics_api: "docker.io/opencontrailnightly/contrail-analytics-api:master-latest"
      contrail_collector: "docker.io/opencontrailnightly/contrail-analytics-collector:master-latest"
      analytics_alarm_gen: "docker.io/opencontrailnightly/contrail-analytics-alarm-gen:master-latest"
      analytics_query_engine: "docker.io/opencontrailnightly/contrail-analytics-query-engine:master-latest"
      analytics_snmp_collector: "docker.io/opencontrailnightly/contrail-analytics-snmp-collector:master-latest"
      contrail_topology: "docker.io/opencontrailnightly/contrail-analytics-snmp-topology:master-latest"
      build_driver_init: "docker.io/opencontrailnightly/contrail-vrouter-kernel-build-init:master-latest"
      vrouter_agent: "docker.io/opencontrailnightly/contrail-vrouter-agent:master-latest"
      vrouter_init_kernel: "docker.io/opencontrailnightly/contrail-vrouter-kernel-init:master-latest"
      vrouter_dpdk: "docker.io/opencontrailnightly/contrail-vrouter-agent-dpdk:master-latest"
      vrouter_init_dpdk: "docker.io/opencontrailnightly/contrail-vrouter-kernel-init-dpdk:master-latest"
      nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:master-latest"
      contrail_status: "docker.io/opencontrailnightly/contrail-status:master-latest"
      node_init: "docker.io/opencontrailnightly/contrail-node-init:master-latest"
      rabbitmq: "docker.io/opencontrailnightly/contrail-external-rabbitmq:master-latest"
      vrouter_plugin_mellanox_init: "docker.io/opencontrailnightly/contrail-vrouter-plugin-mellanox-init-ubuntu:master-latest"
      dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0

  # contrail_env section for all containers
  contrail_env:
    CONTROLLER_NODES: 10.0.2.15
    CLOUD_ORCHESTRATOR: kubernetes
    AAA_MODE: no-auth
    JVM_EXTRA_OPTS: "-Xms1g -Xmx2g"

  node:
    host_os: centos

# Chart level variables like manifests, labels which are local to subchart
# Can be updated from the parent chart like below
# Example of overriding values of subchart, where contrail-vrouter is name of the subchart
contrail-vrouter:
  manifests:
    configmap_vrouter_keystone: false
    job_kubernetes_cni_init: true

contrail-analytics:
  manifests:
    configmap_analytics_keystone: false
    configmap_controller_rabbitmq: false

contrail-controller:
  manifests:
    configmap_controller_keystone: false
    daemonset_kube_manager: true
    configmap_controller_rabbitmq: false

contrail-thirdparty:
  manifests:
    configmap_thirdparty_keystone: false

